"""add memory_utilization to database

Revision ID: aff400a45750
Revises: ef53ad265c44
Create Date: 2026-05-06 14:59:36.280257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff400a45750'
down_revision = 'ef53ad265c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('databases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_utilization', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('databases', schema=None) as batch_op:
        batch_op.drop_column('memory_utilization')

    # ### end Alembic commands ###
